// Code generated by protoc-gen-go. DO NOT EDIT.
// source: stat_view.proto

package stat_view

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AdvertiserPayout struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AffiliatePayment     float32  `protobuf:"fixed32,2,opt,name=affiliate_payment,json=affiliatePayment,proto3" json:"affiliate_payment,omitempty"`
	AdvertiserPayment    float32  `protobuf:"fixed32,3,opt,name=advertiser_payment,json=advertiserPayment,proto3" json:"advertiser_payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdvertiserPayout) Reset()         { *m = AdvertiserPayout{} }
func (m *AdvertiserPayout) String() string { return proto.CompactTextString(m) }
func (*AdvertiserPayout) ProtoMessage()    {}
func (*AdvertiserPayout) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{0}
}
func (m *AdvertiserPayout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvertiserPayout.Unmarshal(m, b)
}
func (m *AdvertiserPayout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvertiserPayout.Marshal(b, m, deterministic)
}
func (dst *AdvertiserPayout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvertiserPayout.Merge(dst, src)
}
func (m *AdvertiserPayout) XXX_Size() int {
	return xxx_messageInfo_AdvertiserPayout.Size(m)
}
func (m *AdvertiserPayout) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvertiserPayout.DiscardUnknown(m)
}

var xxx_messageInfo_AdvertiserPayout proto.InternalMessageInfo

func (m *AdvertiserPayout) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AdvertiserPayout) GetAffiliatePayment() float32 {
	if m != nil {
		return m.AffiliatePayment
	}
	return 0
}

func (m *AdvertiserPayout) GetAdvertiserPayment() float32 {
	if m != nil {
		return m.AdvertiserPayment
	}
	return 0
}

type AdvertiserPayoutFilter struct {
	DateFrom             string   `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               string   `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	UserD                []int32  `protobuf:"varint,3,rep,packed,name=user_d,json=userD,proto3" json:"user_d,omitempty"`
	Currency             string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdvertiserPayoutFilter) Reset()         { *m = AdvertiserPayoutFilter{} }
func (m *AdvertiserPayoutFilter) String() string { return proto.CompactTextString(m) }
func (*AdvertiserPayoutFilter) ProtoMessage()    {}
func (*AdvertiserPayoutFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{1}
}
func (m *AdvertiserPayoutFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvertiserPayoutFilter.Unmarshal(m, b)
}
func (m *AdvertiserPayoutFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvertiserPayoutFilter.Marshal(b, m, deterministic)
}
func (dst *AdvertiserPayoutFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvertiserPayoutFilter.Merge(dst, src)
}
func (m *AdvertiserPayoutFilter) XXX_Size() int {
	return xxx_messageInfo_AdvertiserPayoutFilter.Size(m)
}
func (m *AdvertiserPayoutFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvertiserPayoutFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AdvertiserPayoutFilter proto.InternalMessageInfo

func (m *AdvertiserPayoutFilter) GetDateFrom() string {
	if m != nil {
		return m.DateFrom
	}
	return ""
}

func (m *AdvertiserPayoutFilter) GetDateTo() string {
	if m != nil {
		return m.DateTo
	}
	return ""
}

func (m *AdvertiserPayoutFilter) GetUserD() []int32 {
	if m != nil {
		return m.UserD
	}
	return nil
}

func (m *AdvertiserPayoutFilter) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type AdvertiserPayoutResponse struct {
	Items                []*AdvertiserPayout `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *AdvertiserPayoutResponse) Reset()         { *m = AdvertiserPayoutResponse{} }
func (m *AdvertiserPayoutResponse) String() string { return proto.CompactTextString(m) }
func (*AdvertiserPayoutResponse) ProtoMessage()    {}
func (*AdvertiserPayoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{2}
}
func (m *AdvertiserPayoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdvertiserPayoutResponse.Unmarshal(m, b)
}
func (m *AdvertiserPayoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdvertiserPayoutResponse.Marshal(b, m, deterministic)
}
func (dst *AdvertiserPayoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdvertiserPayoutResponse.Merge(dst, src)
}
func (m *AdvertiserPayoutResponse) XXX_Size() int {
	return xxx_messageInfo_AdvertiserPayoutResponse.Size(m)
}
func (m *AdvertiserPayoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdvertiserPayoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdvertiserPayoutResponse proto.InternalMessageInfo

func (m *AdvertiserPayoutResponse) GetItems() []*AdvertiserPayout {
	if m != nil {
		return m.Items
	}
	return nil
}

type AffiliatePayoutFilter struct {
	DateFrom             string   `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               string   `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	UserId               []int32  `protobuf:"varint,3,rep,packed,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Currency             string   `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AffiliatePayoutFilter) Reset()         { *m = AffiliatePayoutFilter{} }
func (m *AffiliatePayoutFilter) String() string { return proto.CompactTextString(m) }
func (*AffiliatePayoutFilter) ProtoMessage()    {}
func (*AffiliatePayoutFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{3}
}
func (m *AffiliatePayoutFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AffiliatePayoutFilter.Unmarshal(m, b)
}
func (m *AffiliatePayoutFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AffiliatePayoutFilter.Marshal(b, m, deterministic)
}
func (dst *AffiliatePayoutFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AffiliatePayoutFilter.Merge(dst, src)
}
func (m *AffiliatePayoutFilter) XXX_Size() int {
	return xxx_messageInfo_AffiliatePayoutFilter.Size(m)
}
func (m *AffiliatePayoutFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_AffiliatePayoutFilter.DiscardUnknown(m)
}

var xxx_messageInfo_AffiliatePayoutFilter proto.InternalMessageInfo

func (m *AffiliatePayoutFilter) GetDateFrom() string {
	if m != nil {
		return m.DateFrom
	}
	return ""
}

func (m *AffiliatePayoutFilter) GetDateTo() string {
	if m != nil {
		return m.DateTo
	}
	return ""
}

func (m *AffiliatePayoutFilter) GetUserId() []int32 {
	if m != nil {
		return m.UserId
	}
	return nil
}

func (m *AffiliatePayoutFilter) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type AffiliatePayout struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AffiliatePayment     float32  `protobuf:"fixed32,2,opt,name=affiliate_payment,json=affiliatePayment,proto3" json:"affiliate_payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AffiliatePayout) Reset()         { *m = AffiliatePayout{} }
func (m *AffiliatePayout) String() string { return proto.CompactTextString(m) }
func (*AffiliatePayout) ProtoMessage()    {}
func (*AffiliatePayout) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{4}
}
func (m *AffiliatePayout) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AffiliatePayout.Unmarshal(m, b)
}
func (m *AffiliatePayout) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AffiliatePayout.Marshal(b, m, deterministic)
}
func (dst *AffiliatePayout) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AffiliatePayout.Merge(dst, src)
}
func (m *AffiliatePayout) XXX_Size() int {
	return xxx_messageInfo_AffiliatePayout.Size(m)
}
func (m *AffiliatePayout) XXX_DiscardUnknown() {
	xxx_messageInfo_AffiliatePayout.DiscardUnknown(m)
}

var xxx_messageInfo_AffiliatePayout proto.InternalMessageInfo

func (m *AffiliatePayout) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AffiliatePayout) GetAffiliatePayment() float32 {
	if m != nil {
		return m.AffiliatePayment
	}
	return 0
}

type AffiliatePayoutResponse struct {
	Items                []*AffiliatePayout `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *AffiliatePayoutResponse) Reset()         { *m = AffiliatePayoutResponse{} }
func (m *AffiliatePayoutResponse) String() string { return proto.CompactTextString(m) }
func (*AffiliatePayoutResponse) ProtoMessage()    {}
func (*AffiliatePayoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{5}
}
func (m *AffiliatePayoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AffiliatePayoutResponse.Unmarshal(m, b)
}
func (m *AffiliatePayoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AffiliatePayoutResponse.Marshal(b, m, deterministic)
}
func (dst *AffiliatePayoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AffiliatePayoutResponse.Merge(dst, src)
}
func (m *AffiliatePayoutResponse) XXX_Size() int {
	return xxx_messageInfo_AffiliatePayoutResponse.Size(m)
}
func (m *AffiliatePayoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AffiliatePayoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AffiliatePayoutResponse proto.InternalMessageInfo

func (m *AffiliatePayoutResponse) GetItems() []*AffiliatePayout {
	if m != nil {
		return m.Items
	}
	return nil
}

type FinanceTotalFilter struct {
	DateFrom             string   `protobuf:"bytes,1,opt,name=date_from,json=dateFrom,proto3" json:"date_from,omitempty"`
	DateTo               string   `protobuf:"bytes,2,opt,name=date_to,json=dateTo,proto3" json:"date_to,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinanceTotalFilter) Reset()         { *m = FinanceTotalFilter{} }
func (m *FinanceTotalFilter) String() string { return proto.CompactTextString(m) }
func (*FinanceTotalFilter) ProtoMessage()    {}
func (*FinanceTotalFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{6}
}
func (m *FinanceTotalFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinanceTotalFilter.Unmarshal(m, b)
}
func (m *FinanceTotalFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinanceTotalFilter.Marshal(b, m, deterministic)
}
func (dst *FinanceTotalFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinanceTotalFilter.Merge(dst, src)
}
func (m *FinanceTotalFilter) XXX_Size() int {
	return xxx_messageInfo_FinanceTotalFilter.Size(m)
}
func (m *FinanceTotalFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_FinanceTotalFilter.DiscardUnknown(m)
}

var xxx_messageInfo_FinanceTotalFilter proto.InternalMessageInfo

func (m *FinanceTotalFilter) GetDateFrom() string {
	if m != nil {
		return m.DateFrom
	}
	return ""
}

func (m *FinanceTotalFilter) GetDateTo() string {
	if m != nil {
		return m.DateTo
	}
	return ""
}

func (m *FinanceTotalFilter) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

type FinanceTotalResponse struct {
	AffiliatePayment     float32  `protobuf:"fixed32,1,opt,name=affiliate_payment,json=affiliatePayment,proto3" json:"affiliate_payment,omitempty"`
	AdvertiserPayment    float32  `protobuf:"fixed32,2,opt,name=advertiser_payment,json=advertiserPayment,proto3" json:"advertiser_payment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinanceTotalResponse) Reset()         { *m = FinanceTotalResponse{} }
func (m *FinanceTotalResponse) String() string { return proto.CompactTextString(m) }
func (*FinanceTotalResponse) ProtoMessage()    {}
func (*FinanceTotalResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{7}
}
func (m *FinanceTotalResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinanceTotalResponse.Unmarshal(m, b)
}
func (m *FinanceTotalResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinanceTotalResponse.Marshal(b, m, deterministic)
}
func (dst *FinanceTotalResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinanceTotalResponse.Merge(dst, src)
}
func (m *FinanceTotalResponse) XXX_Size() int {
	return xxx_messageInfo_FinanceTotalResponse.Size(m)
}
func (m *FinanceTotalResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FinanceTotalResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FinanceTotalResponse proto.InternalMessageInfo

func (m *FinanceTotalResponse) GetAffiliatePayment() float32 {
	if m != nil {
		return m.AffiliatePayment
	}
	return 0
}

func (m *FinanceTotalResponse) GetAdvertiserPayment() float32 {
	if m != nil {
		return m.AdvertiserPayment
	}
	return 0
}

type ListCompetitionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCompetitionsRequest) Reset()         { *m = ListCompetitionsRequest{} }
func (m *ListCompetitionsRequest) String() string { return proto.CompactTextString(m) }
func (*ListCompetitionsRequest) ProtoMessage()    {}
func (*ListCompetitionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{8}
}
func (m *ListCompetitionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCompetitionsRequest.Unmarshal(m, b)
}
func (m *ListCompetitionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCompetitionsRequest.Marshal(b, m, deterministic)
}
func (dst *ListCompetitionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCompetitionsRequest.Merge(dst, src)
}
func (m *ListCompetitionsRequest) XXX_Size() int {
	return xxx_messageInfo_ListCompetitionsRequest.Size(m)
}
func (m *ListCompetitionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCompetitionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListCompetitionsRequest proto.InternalMessageInfo

type Competition struct {
	UserId               int32    `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Approve              int32    `protobuf:"varint,2,opt,name=approve,proto3" json:"approve,omitempty"`
	Chance               float32  `protobuf:"fixed32,3,opt,name=chance,proto3" json:"chance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Competition) Reset()         { *m = Competition{} }
func (m *Competition) String() string { return proto.CompactTextString(m) }
func (*Competition) ProtoMessage()    {}
func (*Competition) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{9}
}
func (m *Competition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Competition.Unmarshal(m, b)
}
func (m *Competition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Competition.Marshal(b, m, deterministic)
}
func (dst *Competition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Competition.Merge(dst, src)
}
func (m *Competition) XXX_Size() int {
	return xxx_messageInfo_Competition.Size(m)
}
func (m *Competition) XXX_DiscardUnknown() {
	xxx_messageInfo_Competition.DiscardUnknown(m)
}

var xxx_messageInfo_Competition proto.InternalMessageInfo

func (m *Competition) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *Competition) GetApprove() int32 {
	if m != nil {
		return m.Approve
	}
	return 0
}

func (m *Competition) GetChance() float32 {
	if m != nil {
		return m.Chance
	}
	return 0
}

type ListCompetitionsResponse struct {
	Competitions         []*Competition `protobuf:"bytes,1,rep,name=competitions,proto3" json:"competitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListCompetitionsResponse) Reset()         { *m = ListCompetitionsResponse{} }
func (m *ListCompetitionsResponse) String() string { return proto.CompactTextString(m) }
func (*ListCompetitionsResponse) ProtoMessage()    {}
func (*ListCompetitionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_stat_view_04c6ddf8613d6f91, []int{10}
}
func (m *ListCompetitionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCompetitionsResponse.Unmarshal(m, b)
}
func (m *ListCompetitionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCompetitionsResponse.Marshal(b, m, deterministic)
}
func (dst *ListCompetitionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCompetitionsResponse.Merge(dst, src)
}
func (m *ListCompetitionsResponse) XXX_Size() int {
	return xxx_messageInfo_ListCompetitionsResponse.Size(m)
}
func (m *ListCompetitionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCompetitionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListCompetitionsResponse proto.InternalMessageInfo

func (m *ListCompetitionsResponse) GetCompetitions() []*Competition {
	if m != nil {
		return m.Competitions
	}
	return nil
}

func init() {
	proto.RegisterType((*AdvertiserPayout)(nil), "stat_view.AdvertiserPayout")
	proto.RegisterType((*AdvertiserPayoutFilter)(nil), "stat_view.AdvertiserPayoutFilter")
	proto.RegisterType((*AdvertiserPayoutResponse)(nil), "stat_view.AdvertiserPayoutResponse")
	proto.RegisterType((*AffiliatePayoutFilter)(nil), "stat_view.AffiliatePayoutFilter")
	proto.RegisterType((*AffiliatePayout)(nil), "stat_view.AffiliatePayout")
	proto.RegisterType((*AffiliatePayoutResponse)(nil), "stat_view.AffiliatePayoutResponse")
	proto.RegisterType((*FinanceTotalFilter)(nil), "stat_view.FinanceTotalFilter")
	proto.RegisterType((*FinanceTotalResponse)(nil), "stat_view.FinanceTotalResponse")
	proto.RegisterType((*ListCompetitionsRequest)(nil), "stat_view.ListCompetitionsRequest")
	proto.RegisterType((*Competition)(nil), "stat_view.Competition")
	proto.RegisterType((*ListCompetitionsResponse)(nil), "stat_view.ListCompetitionsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StatViewClient is the client API for StatView service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StatViewClient interface {
	GetAdvertiserPayout(ctx context.Context, in *AdvertiserPayoutFilter, opts ...grpc.CallOption) (*AdvertiserPayoutResponse, error)
	GetAffiliatePayout(ctx context.Context, in *AffiliatePayoutFilter, opts ...grpc.CallOption) (*AffiliatePayoutResponse, error)
	GetFinanceTotal(ctx context.Context, in *FinanceTotalFilter, opts ...grpc.CallOption) (*FinanceTotalResponse, error)
	ListCompetitions(ctx context.Context, in *ListCompetitionsRequest, opts ...grpc.CallOption) (*ListCompetitionsResponse, error)
}

type statViewClient struct {
	cc *grpc.ClientConn
}

func NewStatViewClient(cc *grpc.ClientConn) StatViewClient {
	return &statViewClient{cc}
}

func (c *statViewClient) GetAdvertiserPayout(ctx context.Context, in *AdvertiserPayoutFilter, opts ...grpc.CallOption) (*AdvertiserPayoutResponse, error) {
	out := new(AdvertiserPayoutResponse)
	err := c.cc.Invoke(ctx, "/stat_view.StatView/GetAdvertiserPayout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statViewClient) GetAffiliatePayout(ctx context.Context, in *AffiliatePayoutFilter, opts ...grpc.CallOption) (*AffiliatePayoutResponse, error) {
	out := new(AffiliatePayoutResponse)
	err := c.cc.Invoke(ctx, "/stat_view.StatView/GetAffiliatePayout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statViewClient) GetFinanceTotal(ctx context.Context, in *FinanceTotalFilter, opts ...grpc.CallOption) (*FinanceTotalResponse, error) {
	out := new(FinanceTotalResponse)
	err := c.cc.Invoke(ctx, "/stat_view.StatView/GetFinanceTotal", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statViewClient) ListCompetitions(ctx context.Context, in *ListCompetitionsRequest, opts ...grpc.CallOption) (*ListCompetitionsResponse, error) {
	out := new(ListCompetitionsResponse)
	err := c.cc.Invoke(ctx, "/stat_view.StatView/ListCompetitions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatViewServer is the server API for StatView service.
type StatViewServer interface {
	GetAdvertiserPayout(context.Context, *AdvertiserPayoutFilter) (*AdvertiserPayoutResponse, error)
	GetAffiliatePayout(context.Context, *AffiliatePayoutFilter) (*AffiliatePayoutResponse, error)
	GetFinanceTotal(context.Context, *FinanceTotalFilter) (*FinanceTotalResponse, error)
	ListCompetitions(context.Context, *ListCompetitionsRequest) (*ListCompetitionsResponse, error)
}

func RegisterStatViewServer(s *grpc.Server, srv StatViewServer) {
	s.RegisterService(&_StatView_serviceDesc, srv)
}

func _StatView_GetAdvertiserPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdvertiserPayoutFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatViewServer).GetAdvertiserPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stat_view.StatView/GetAdvertiserPayout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatViewServer).GetAdvertiserPayout(ctx, req.(*AdvertiserPayoutFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatView_GetAffiliatePayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AffiliatePayoutFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatViewServer).GetAffiliatePayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stat_view.StatView/GetAffiliatePayout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatViewServer).GetAffiliatePayout(ctx, req.(*AffiliatePayoutFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatView_GetFinanceTotal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinanceTotalFilter)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatViewServer).GetFinanceTotal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stat_view.StatView/GetFinanceTotal",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatViewServer).GetFinanceTotal(ctx, req.(*FinanceTotalFilter))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatView_ListCompetitions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCompetitionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatViewServer).ListCompetitions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/stat_view.StatView/ListCompetitions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatViewServer).ListCompetitions(ctx, req.(*ListCompetitionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StatView_serviceDesc = grpc.ServiceDesc{
	ServiceName: "stat_view.StatView",
	HandlerType: (*StatViewServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAdvertiserPayout",
			Handler:    _StatView_GetAdvertiserPayout_Handler,
		},
		{
			MethodName: "GetAffiliatePayout",
			Handler:    _StatView_GetAffiliatePayout_Handler,
		},
		{
			MethodName: "GetFinanceTotal",
			Handler:    _StatView_GetFinanceTotal_Handler,
		},
		{
			MethodName: "ListCompetitions",
			Handler:    _StatView_ListCompetitions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "stat_view.proto",
}

func init() { proto.RegisterFile("stat_view.proto", fileDescriptor_stat_view_04c6ddf8613d6f91) }

var fileDescriptor_stat_view_04c6ddf8613d6f91 = []byte{
	// 515 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x13, 0x9c, 0x36, 0x53, 0xa4, 0xa4, 0x0b, 0x4d, 0x4c, 0x2a, 0x84, 0x59, 0x2e, 0x91,
	0x10, 0x15, 0x94, 0x1b, 0xb7, 0x0a, 0x94, 0x0a, 0x01, 0x52, 0xe5, 0x56, 0x85, 0x03, 0xc8, 0x5a,
	0xec, 0x89, 0x58, 0x29, 0xf6, 0x9a, 0xf5, 0x24, 0x55, 0x8e, 0x70, 0xe1, 0x57, 0x23, 0x21, 0x7f,
	0xc4, 0xdd, 0x38, 0x38, 0x12, 0x2a, 0xc7, 0x99, 0xdd, 0x99, 0x79, 0xf3, 0xde, 0xdb, 0x85, 0x5e,
	0x4a, 0x82, 0xfc, 0x85, 0xc4, 0xeb, 0xe3, 0x44, 0x2b, 0x52, 0xac, 0x5b, 0x25, 0xf8, 0x2f, 0x0b,
	0xfa, 0xa7, 0xe1, 0x02, 0x35, 0xc9, 0x14, 0xf5, 0xb9, 0x58, 0xaa, 0x39, 0xb1, 0x21, 0xec, 0xce,
	0x53, 0xd4, 0xbe, 0x0c, 0x1d, 0xcb, 0xb5, 0xc6, 0xb6, 0xd7, 0xc9, 0xc2, 0xb7, 0x21, 0x7b, 0x0a,
	0x07, 0x62, 0x3a, 0x95, 0x33, 0x29, 0x08, 0xfd, 0x44, 0x2c, 0x23, 0x8c, 0xc9, 0x69, 0xb9, 0xd6,
	0xb8, 0xe5, 0xf5, 0xab, 0x83, 0xf3, 0x22, 0xcf, 0x9e, 0x01, 0x13, 0x55, 0xe7, 0xea, 0x76, 0x3b,
	0xbf, 0x7d, 0x20, 0xcc, 0x99, 0xd9, 0x01, 0xff, 0x61, 0xc1, 0xa0, 0x8e, 0x64, 0x22, 0x67, 0x84,
	0x9a, 0x1d, 0x41, 0x37, 0xcc, 0x26, 0x4e, 0xb5, 0x8a, 0x72, 0x44, 0x5d, 0x6f, 0x2f, 0x4b, 0x4c,
	0xb4, 0x8a, 0x32, 0xb0, 0xf9, 0x21, 0xa9, 0x1c, 0x49, 0xd7, 0xeb, 0x64, 0xe1, 0xa5, 0x62, 0x87,
	0x90, 0xc3, 0xf6, 0x43, 0xa7, 0xed, 0xb6, 0xc7, 0xb6, 0x67, 0x67, 0xd1, 0x1b, 0x36, 0x82, 0xbd,
	0x60, 0xae, 0x35, 0xc6, 0xc1, 0xd2, 0xb9, 0x53, 0xf4, 0x5a, 0xc5, 0xfc, 0x03, 0x38, 0x75, 0x08,
	0x1e, 0xa6, 0x89, 0x8a, 0x53, 0x64, 0x2f, 0xc0, 0x96, 0x84, 0x51, 0xea, 0x58, 0x6e, 0x7b, 0xbc,
	0x7f, 0x72, 0x74, 0x7c, 0xc3, 0xea, 0x46, 0x4d, 0x71, 0x93, 0xff, 0xb4, 0xe0, 0xf0, 0xd4, 0xa0,
	0xe5, 0xb6, 0x1b, 0x19, 0xba, 0x14, 0x2b, 0xad, 0x74, 0xd9, 0xb6, 0xd3, 0x47, 0xe8, 0xd5, 0x30,
	0xfc, 0x1f, 0x7d, 0xf9, 0x3b, 0x18, 0xd6, 0x1a, 0x57, 0x5c, 0x3d, 0x5f, 0xe7, 0x6a, 0x64, 0x72,
	0x55, 0x2b, 0x29, 0xa9, 0x9a, 0x02, 0x9b, 0xc8, 0x58, 0xc4, 0x01, 0x5e, 0x2a, 0x12, 0xb3, 0x5b,
	0xd1, 0x64, 0xb2, 0xd1, 0xae, 0xb1, 0xa1, 0xe1, 0xbe, 0x39, 0xa7, 0x42, 0xfc, 0xd7, 0xcd, 0xad,
	0x7f, 0x72, 0x76, 0xab, 0xc9, 0xd9, 0x0f, 0x60, 0xf8, 0x5e, 0xa6, 0xf4, 0x5a, 0x45, 0x09, 0x92,
	0x24, 0xa9, 0xe2, 0xd4, 0xc3, 0xef, 0x73, 0x4c, 0x89, 0x7f, 0x82, 0x7d, 0x23, 0xdd, 0x2c, 0x8c,
	0x03, 0xbb, 0x22, 0x49, 0xb4, 0x5a, 0x60, 0x3e, 0xc6, 0xf6, 0x56, 0x21, 0x1b, 0x40, 0x27, 0xf8,
	0x96, 0xed, 0x53, 0xbe, 0xac, 0x32, 0xe2, 0x57, 0xe0, 0x6c, 0x0e, 0x2d, 0x97, 0x7d, 0x05, 0x77,
	0x03, 0x23, 0x5f, 0xaa, 0x34, 0x30, 0x54, 0x32, 0xca, 0xbc, 0xb5, 0xbb, 0x27, 0xbf, 0x5b, 0xb0,
	0x77, 0x41, 0x82, 0xae, 0x24, 0x5e, 0x33, 0x1f, 0xee, 0x9d, 0x21, 0x6d, 0xfc, 0x1f, 0x8f, 0xb7,
	0xbc, 0x8d, 0x42, 0xd9, 0xd1, 0x93, 0x6d, 0xcf, 0xa7, 0xc4, 0xc9, 0x77, 0xd8, 0x67, 0x60, 0xd9,
	0x80, 0x9a, 0x7f, 0xdd, 0x66, 0x3f, 0x95, 0xed, 0xf9, 0x16, 0xc7, 0xdd, 0x74, 0xbf, 0x80, 0xde,
	0x19, 0x92, 0xe9, 0x07, 0xf6, 0xd0, 0x28, 0xdc, 0x34, 0xe4, 0xe8, 0x51, 0xc3, 0xb1, 0xd1, 0xf4,
	0x0b, 0xf4, 0xeb, 0xc4, 0x33, 0x13, 0x4e, 0x83, 0x15, 0xd6, 0x18, 0x69, 0x52, 0x8e, 0xef, 0x7c,
	0xed, 0xe4, 0x5f, 0xf8, 0xcb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x73, 0xa2, 0x11, 0x5b, 0xd5,
	0x05, 0x00, 0x00,
}
